# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: flake8
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: poetry run mypy --strict-optional --disallow-untyped-defs --disallow-untyped-calls .
    pass_filenames: false
    language: system
  - id: pytest
    name: pytest
    entry: poetry run pytest
    pass_filenames: false
    language: system
